// Generated by tools/amber.py. Do not edit.
const FILTER_URLS = {
  amber: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='amber' color-interpolation-filters='sRGB' filterUnits='userSpaceOnUse' x='-1000000' y='-1000000' width='2000000' height='100000000'%3E%3CfeColorMatrix type='matrix' values='0.2126 0.7152 0.0722 0 0 0.1099 0.3695 0.0373 0 0 0 0 0 0 0 0 0 0 1 0'/%3E%3C/filter%3E%3C/svg%3E#amber",
  warm: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='warm' color-interpolation-filters='sRGB' filterUnits='userSpaceOnUse' x='-1000000' y='-1000000' width='2000000' height='100000000'%3E%3CfeColorMatrix type='matrix' values='1 0 0 0 0 0 0.5167 0 0 0 0 0 0 0 0 0 0 0 1 0'/%3E%3C/filter%3E%3C/svg%3E#warm",
};
const DEFAULT_DIM = 70;
