#!/usr/bin/env python3
"""The Amber look in numbers, and the files derived from it.

Amber = gray, then tinted like a black body at 1900 K, the coolest
temperature that already has no blue: red kept whole, about half the green,
no blue at all. The same numbers go into the browser stylesheet and the two
desktop shaders, so the three filters cannot drift apart.

Run without arguments to rewrite the generated files.
"""
import math
import pathlib
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Luminance of a colour, Rec. 709.
LUMA = (0.2126, 0.7152, 0.0722)


def tint(kelvin: int = 1900) -> tuple[float, float, float]:
    """Channel multipliers of a black body (Tanner Helland's fit), red normalised to 1."""
    t = kelvin / 100
    green = (99.4708025861 * math.log(t) - 161.1195681661) / 255
    blue = 0.0 if t <= 19 else (138.5177312231 * math.log(t - 10) - 305.0447927307) / 255
    return (1.0, round(min(1.0, max(0.0, green)), 4), round(min(1.0, max(0.0, blue)), 4))


TINT = tint()


def matrix(gray: bool) -> str:
    """feColorMatrix values: 4 rows of 5."""
    rows = []
    for channel in range(3):
        if gray:
            row = [round(TINT[channel] * w, 4) for w in LUMA]
        else:
            row = [TINT[channel] if i == channel else 0 for i in range(3)]
        rows.append(row + [0, 0])
    rows.append([0, 0, 0, 1, 0])
    return " ".join(f"{v:g}" for row in rows for v in row)


# An SVG filter only covers a region around the element's own box (120 % of it by
# default). The root box of a short page stops under its last line, and Chromium then
# leaves the rest of the window unfiltered: white. So the region is spelled out, far
# larger than any page.
REGION = "filterUnits='userSpaceOnUse' x='-1000000' y='-1000000' width='2000000' height='100000000'"


def filter_url(name: str, gray: bool) -> str:
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg'>"
        f"<filter id='{name}' color-interpolation-filters='sRGB' {REGION}>"
        f"<feColorMatrix type='matrix' values='{matrix(gray)}'/>"
        "</filter></svg>"
    )
    return "data:image/svg+xml," + urllib.parse.quote(svg, safe="='/: ") + "#" + name


DEFAULT_DIM = 70


def browser_css() -> str:
    on = 'html:not([data-readers-night~="off"])'
    return f"""/* Generated by tools/amber.py. Do not edit. */

/* Gray, then amber, then dimmed. On the root element a filter covers the whole page,
   frames and video included, and leaves fixed elements where they are.
   The browser injects this before a page's first paint; content.js then replaces it,
   through the root's own style, when the user's settings are not these. */
{on} {{
  filter: url("{filter_url('amber', True)}") brightness({DEFAULT_DIM / 100:g}) !important;
}}

/* A page that sets no background at all is drawn on the browser's bare canvas, which
   no filter reaches: it would stay white. Zero specificity, so any background the page
   gives its root wins; content.js lifts this when the body brings its own. */
:where({on}:not([data-readers-night-bg])) {{
  background-color: Canvas;
}}
"""


def browser_js() -> str:
    return f"""// Generated by tools/amber.py. Do not edit.
const FILTER_URLS = {{
  amber: "{filter_url('amber', True)}",
  warm: "{filter_url('warm', False)}",
}};
const DEFAULT_DIM = {DEFAULT_DIM};
"""


def glsl_constants() -> str:
    return (
        f"const vec3 LUMA = vec3({LUMA[0]}, {LUMA[1]}, {LUMA[2]});\n"
        f"const vec3 TINT = vec3({TINT[0]:.4f}, {TINT[1]:.4f}, {TINT[2]:.4f});\n"
    )


if __name__ == "__main__":
    (ROOT / "browser" / "filter.css").write_text(browser_css())
    (ROOT / "browser" / "filter-urls.js").write_text(browser_js())
    print("tint", TINT)
    print(glsl_constants(), end="")
